# Build settings
markdown: redcarpet

# Site settings
title: "Mediator"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: a06kin@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Шу'
author: 'Шу'
author_image: "/assets/images/author.jpg"

paginate: 7
paginate_path: "/list/page:num/"

gems:
  [jekyll-paginate]

exclude:          	 ["vendor", ".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

url: "https://quale.herokuapp.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
# twitter_handle: '@a06kin'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
# social:
#   - icon:	twitter
#     url:	https://twitter.com/a06kin
#     desc: Follow me on twitter
#     share_url: http://twitter.com/share
#     share_title: ?text=
#     share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/a06kin
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
